version: '3'

services:

  nextcloud:
    image: dotriver/nextcloud
    environment:
        - DATABASE_HOST=mariadb
        - DATABASE_PORT=3306
        - DATABASE_NAME=nextcloud
        - DATABASE_USERNAME=nextcloud
        - DATABASE_PASSWORD=password
        - ADMIN_USERNAME=admin
        - ADMIN_PASSWORD=password
        - TRUSTED_DOMAIN_0=127.0.0.1:8080
    ports:
      - 8080:80
    volumes:
      - nextcloud-data:/var/www/nextcloud/
    networks:
      default:
  
  mariadb:
    image: dotriver/mariadb
    environment:
      - ROOT_PASSWORD=password
      - DB_0_NAME=nextcloud
      - DB_0_PASS=password
    ports:
      - 3306:3306
      - 8081:80
    volumes:
      - mariadb-data:/var/lib/mysql/
      - mariadb-config:/etc/mysql/
    networks:
      default:
    
volumes:
    nextcloud-data:
    mariadb-data:
    mariadb-config:
